//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manual_inicioUTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion_Actividad
    {
        public int idInscripcion { get; set; }
        public int idActividad { get; set; }
        public int puntos { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Inscripcion Inscripcion { get; set; }
    }
}
